version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 017820697088.dkr.ecr.ap-southeast-1.amazonaws.com/myapp-ec2
      - REPOSITORY_URI=017820697088.dkr.ecr.ap-southeast-1.amazonaws.com/myapp-ec2
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Building image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - echo Pushing to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"my-app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - appspec.yml
    - scripts/deploy.sh
    - imagedefinitions.json